# Generated by Django 5.0.1 on 2024-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subplan_highlight_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('user_feedback', models.CharField(max_length=122)),
            ],
        ),
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Menu',
        ),
        migrations.RemoveField(
            model_name='subplanfeature',
            name='subplan',
        ),
        migrations.DeleteModel(
            name='SubPlan',
        ),
        migrations.DeleteModel(
            name='SubPlanFeature',
        ),
    ]
